---
title: "Data Analysis of HIV/AIDS Diagnoses in NYC"
author: "Tian Li(tl2882) / Huaqing Xi(hx2263) / Shuwei Liu(sl4471) / Yueming Kou(yk2826) / Yizhi Ma(ym2715)"
output:
  html_document: 
    toc: true
    toc_float: true
---

# Overview
<iframe width="560" height="315" src="https://www.youtube.com/embed/LZtj8-rg8s0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Background and Objectives  
Infection by human immunodeficiency virus (HIV) may lead to acquired immunodeficiency syndrome (AIDS) and continues to be a global public health problem, with an estimated 37 million individuals worldwide who are HIV-positive. New York City has the oldest and largest HIV epidemic in the United States history, and it also so leads the nation in the number of new HIV cases nowadays.  
  
In this project, we aim to study the relationships between different characteristics of patients and the HIV/AIDS Diagnosis Outcome in New York City from 2011 to 2015.

# Data Sources

### Main data

HIV/AIDS Diagnoses by Neighborhood, Age Group, and Race/Ethnicity from NYC open data. [[website](https://data.cityofnewyork.us/Health/DOHMH-HIV-AIDS-Annual-Report/fju2-rdad)]

**Data discription:**

Data reported to the HIV Epidemiology and Field Services Program by June 30, 2016. All data shown are for people ages 13 and older. Borough-wide and citywide totals may include cases assigned to a borough with an unknown UHF or assigned to NYC with an unknown borough, respectively. Therefore, UHF totals may not sum to borough totals and borough totals may not sum to citywide totals."



### Other data


* Shapefile of NYC Zip Codes - tabulation areas provided by NYC Department of Information Technology & Telecommunications (DOITT) [[website](http://data.beta.nyc/dataset/3bf5fb73-edb5-4b05-bb29-7c95f4a727fc/resource/6df127b1-6d04-4bb7-b983-07402a2c3f90)]

* Zip code of United Hospital Fund neighborhood [[website](https://www1.nyc.gov/assets/doh/downloads/pdf/data/appb.pdf)]

* 2011-2015 American Community Survey (ACS) Public Use Microdata Sample (PUMS). [[website](https://factfinder.census.gov/faces/tableservices/jsf/pages/productview.xhtml?pid=ACS_pums_csv_2011_2015&prodType=document)]

**PUMS data wrangling:**

The raw dataset is super large with hundreds of variables, so we select it based on our target variables - location and total person income. The selected dataset is saved as “[selected_pums.csv](./data/selected_pums.csv)” in the data folder under our R project.
The location data from 2011 ACS is based on Public Use Microdata Area Code (PUMA) 2000, while the definition for PUMA 2000 is nowhere to be found. This is why we exclude the income data from 2011.  
  
For the 2012-2015 PUMS data, we transfer the PUMA 2010 into zipcode for a better visualization on the NYC map. The transform is based on the following two datasets.

* [ZCTA10 to PUMA10](http://faculty.baruch.cuny.edu/geoportal/resources/nyc_geog/nyc_zcta10_to_puma10.xls)
* [ZIP Code to ZCTA10](http://faculty.baruch.cuny.edu/geoportal/resources/nyc_geog/zip_to_zcta10_nyc_revised.xls)

# Method

After archiving our main data “HIV/AIDS Diagnoses by Neighborhood, Age Group, and Race/Ethnicity” from NYC open data, we tidied it using R. Multiple linear regression models are fitted around two outcomes:  The number of HIV diagnosis and Death rate related to HIV. Three Geomaps were created to show the geographical distribution and differences of HIV diagnosis, HIV rate and income between each United Hospital Funded Neighborhood.


# Results

* ### [Visulizations](visual.html)


* ### [Multiple Linear Regression Models](regression.html)


**Outcome1: The number of HIV diagnosis**

Model1:

*HIV_diagnoses* = 0.983 + 0.297*I(borough = Brooklyn)* + 3.091*I(borough = Manhattan)* - 1.245*I(borough = Queens)* - 4.376*I(borough = Staten Island)* + 6.083*I(male)* + 9.600*I(age20-29)* + 6.870*I(age30-39)* + 4.627*I(age40-49)* + 2.355*I(age50-59)* + 0.427*I(age60+)*

Model2:

*HIV_diagnoses* = 5.143 + 0.357*I(borough = Brooklyn)* + 3.710*I(borough = Manhattan)* - 1.494*I(borough = Queens)* - 5.251*I(borough = Staten Island)* + 7.299*I(male)* - 3.628*I(Asian/Pacific Islander)* + 7.304*I(Black)* + 5.399*I(Latino/Hispanic)* - 5.008*I(Other/Unknown)* 

**Outcome2: Death rate related to HIV**

Model3:

*HIV_related_death_rate* = 2.249 + 0.100*I(borough = Brooklyn)* + 0.118*I(borough = Manhattan)* - 1.007*I(borough = Queens)* + 2.902*I(borough = Staten Island)* - 0.221*I(male)* + 2.625*I(age20-29)* + 2.632*I(age30-39)* + 3.357*I(age40-49)* + 4.893*I(age50-59)* + 8.148*I(age60+)*

Model4:

*HIV_related_death_rate* = 4.780 - 1.083*I(borough = Brooklyn)* + 0.375*I(borough = Manhattan)* - 1.080*I(borough = Queens)* + 2.283*I(borough = Staten Island)* + 0.220*I(male)* - 0.183*I(Asian/Pacific Islander)* + 0.430*I(Black)* + 1.281*I(Latino/Hispanic)* - 2.153*I(Other/Unknown)* 

* ### [Geomaps](geo_plotly.html)


# Conclusion

1. Overall, female has a lower possibility to be diagnosed as HIV and a higher possibility of death due to HIV infection than any another groups.

2. Most infection of HIV occurred between 20 and 29 years old.

3. The rates of new HIV infection among black people and Latino/Hispanic are higher than other race groups.

4. The total HIV incidences in NYC declined from 2011 to 2015.

5. The impact of income on both the number of HIV diagnosis and death rate related to HIV is not significant.

# Screencast

Screencast of our project can be found [here](https://www.youtube.com/watch?v=LZtj8-rg8s0&feature=youtu.be).

# Email

Mail to: _[Tian Li](mailto:tl2882@cumc.columbia.edu) / [Shuwei Liu](mailto:sl4471@cumc.columbia.edu) / [Huaqing Xi](mailto:hx2263@cumc.columbia.edu) / [Yueming Kou](mailto:yk2826@cumc.columbia.edu) / [Yizhi Ma](mailto:ym2715@cumc.columbia.edu)_


